/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#c3c0ff",
        "secondary": "#ffb1c0",
        "tertiary": "#ffb86b",
        "background": "#131315",
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1b1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#303032",
        "outline": "#918fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c3c0ff",
        "primary-container": "#5851db",
        "on-primary": "#1e00a5",
        "on-primary-container": "#e4e0ff",
        "inverse-primary": "#5149d4",
        "on-secondary": "#660029",
        "secondary-container": "#b7004f",
        "on-secondary-container": "#ffc6d0",
        "on-tertiary": "#492900",
        "tertiary-container": "#935800",
        "on-tertiary-container": "#ffdfc1",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#382cbb",
        "secondary-fixed": "#ffd9df",
        "secondary-fixed-dim": "#ffb1c0",
        "on-secondary-fixed": "#3f0017",
        "on-secondary-fixed-variant": "#90003d",
        "tertiary-fixed": "#ffdcbc",
        "tertiary-fixed-dim": "#ffb86b",
        "on-tertiary-fixed": "#2c1700",
        "on-tertiary-fixed-variant": "#683d00",
        "surface-variant": "#353437"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "gutter": "12px",
        "margin-desktop": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "stat-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["32px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "stat-lg": ["28px", { "lineHeight": "1", "fontWeight": "800" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "label-bold": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
